### ISSUE TITLE
SilentExitException

### ISSUE THREAD

**Issue by thehunt100** [fabioformosa/quartz-manager-demo#1]
Hi when I start it throws an 

	static void exitCurrentThread() {
		throw new SilentExitException();
	}

any idea?

![Screenshot from 2021-06-26 08-33-04](https://user-images.githubusercontent.com/76201510/123497696-28361b00-d659-11eb-9f2e-42e335e5174d.png)

**Comment by thehunt100** [comment]
This solved the problem for me

    	System.setProperty("spring.devtools.restart.enabled", "false");

**Comment by fabioformosa** [comment]
Hi thehunt100,
it's not an issue of Quartz Manager, but a known issue of Eclipse when you start a project, which includes spring devtool lib, in debug mode.
Look at this: https://stackoverflow.com/questions/32770884/breakpoint-at-throw-new-silentexitexception-in-eclipse-spring-boot

Thank you to have reported your solution!
