### ISSUE TITLE
Demo URL to quartz-manager-ui is wrong

### ISSUE THREAD

**Issue by rwellman-ats** [fabioformosa/quartz-manager-demo#2]
On your readme, the URL for the frontend is missing the context "/demo".  

It should be as follows:
http://localhost:8080/demo/quartz-manager-ui/index.html

**Comment by rwellman-ats** [comment]
p.s.  Same with the swagger page; it should be as follows:
http://localhost:8080/demo/swagger-ui.html

**Comment by fabioformosa** [comment]
Oh, thank you. Fixed!
